### ISSUE TITLE
The page doen't fit very well in dark mode

### ISSUE THREAD

**Issue by Michaelzhouisnotwhite** [jhildenbiddle/typora-themeable#2]
![image](https://user-images.githubusercontent.com/52443370/196622961-fd825b2d-31cf-41e5-aed4-7c0f1e8cd341.png)

**Comment by jhildenbiddle** [comment]
Hi @Michaelzhouisnotwhite.

Your screenshot does not look like Typora Themeable. I believe you are either using a different theme or you have custom settings that are causing a conflict.

**Comment by ReykerBlack** [comment]
Confirmed for _dark_ and _light_ themes:

1. **File > Preferences > Appearance**
2. In the section **Window Style** check **Unibody**
3. Restart the application
4. In the upper left corner, where the file name is indicated, click on $\equiv$

**Comment by jhildenbiddle** [comment]
My apologies, @ReykerBlack. Thanks for following up with more detail.

This is the first time I've seen the "Unibody" option. As a macOS user, I am less familiar with the Windows and Linux versions of Typora which is why I missed this. The macOS version has a similar windows style option called "Seamless" that has been accounted for, but clearly some work needs to be done to support the "Unibody" option on Windows. 

I'll take care of this in the next day or two. Thanks again.

**Comment by brandon-hurler** [comment]
I am having the same issue as well. I went to investigate the base themes and they look to have errors in them. I can see missing attributes in lines 297, 299, 321, 400, 402, 407, 408, and 416. Are these related or should I open a separate issue for those?

**Comment by jhildenbiddle** [comment]
Fixed in v1.0.3.

Thanks for being patient with this one!
