### ISSUE TITLE
Source code mode: Incorrect size for heading when using setext

### ISSUE THREAD

**Issue by cmeeren** [jhildenbiddle/typora-themeable#4]
This is a screenshot from source code mode:

<img width="211" alt="image" src="https://user-images.githubusercontent.com/7766733/213874207-6a632bfe-64f2-4459-a8aa-22dbdbef5eb0.png">

As you can see, the increased font size for the heading applies only to the setext-style underline (the dashes), not the actual heading text ("Windows settings"). The heading size should apply to both (in other words, they should have the same length).

**Comment by jhildenbiddle** [comment]
Typora's source code mode does not render text in a monospace font, therefore the heading text and the dashes used beneath them will not be the same length.

Here is a screenshot using Typora's "GitHub" theme for comparison:

<img width="150" src="https://user-images.githubusercontent.com/442527/213901912-9b0587ee-f9f2-41bc-b9a3-65ef93f22097.png">

Notice that the heading text and dashes (pink) are not the same length. This is because they are rendered using the OpenSans font. Notice that the inline code blocks are the same length. This is because they are rendered using a monospace font named "Lucida Console".

**Comment by cmeeren** [comment]
Thanks for the clarification. That explains it. Are you saying that themes do not have any control over the font used in source code mode?

**Comment by cmeeren** [comment]
Hi again,

Another screenshot (using Themeable): This does not seem to be about the fonts used being proportional, but rather (as reported) the font size.

<img width="376" alt="image" src="https://user-images.githubusercontent.com/7766733/213909029-41885ed9-16aa-47ce-9024-907de2786f92.png">

As you can see, both the first-level and second-level heading texts are the same size as the normal text, even though the underline for the level-1 heading is bigger than the underline for the level-2 heading (which to me looks bigger again than the normal text). Furthermore, all the text here seems very much monospace to me, not proportional. They are definitely not sans-serif, like OpenSans is.

**Comment by cmeeren** [comment]
Also, here is how it looks with Typora's GitHub theme when I try it. As you can see, it lines up:

<img width="184" alt="image" src="https://user-images.githubusercontent.com/7766733/213909253-ce1abc63-6709-43d1-a244-d1878e3fd793.png">
